// swift-tools-version: 6.0
//
// capnp-swift: Cap'n Proto RPC for Swift apps on Apple platforms.
//
// The RPC core is capnp-zig (hash-pinned in core/build.zig.zon), built into
// the static CapnpCore.xcframework by `cd core && mise exec -- zig build
// xcframework`. Build that first; SwiftPM only links it.
//
// Packaging rules (plan §10): the XCFramework is static and ships no dynamic
// product; never bundle compiler-rt; never strip its DWARF. `platforms` lists
// only what ships: the XCFramework has a macOS slice only until M5 adds the
// iOS slices (they need capnp-zig handoff H1); then add `.iOS(.v18)` (D2).
import PackageDescription

let package = Package(
    name: "capnp-swift",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        // Pure-Swift message reader/builder (no Zig). M1 ships the subset the
        // MVP needs; M3 completes it.
        .library(name: "Capnp", targets: ["Capnp"]),
        // RPC runtime over the C ABI in CapnpCore.
        .library(name: "CapnpRPC", targets: ["CapnpRPC"]),
        // Network.framework transports (TCP in M1).
        .library(name: "CapnpNW", targets: ["CapnpNW"]),
        // M1 interop: the Swift side of `just mvp-e2e` (prints TAP).
        .executable(name: "mvp-e2e", targets: ["mvp-e2e"]),
    ],
    targets: [
        // Local path for development. Releases switch to
        // .binaryTarget(url:checksum:) (plan §10 release ceremony, M7).
        .binaryTarget(
            name: "CapnpCore",
            path: "CapnpCore.xcframework"
        ),
        .target(
            name: "Capnp"
        ),
        .target(
            name: "CapnpRPC",
            dependencies: ["CapnpCore", "Capnp"]
        ),
        .target(
            name: "CapnpNW",
            dependencies: ["CapnpRPC"]
        ),
        // Hand-written bindings for interop/schemas/mvp.capnp (plan §8, M1).
        // M3's capnpc-swift replaces them with generated code.
        .target(
            name: "CapnpMVP",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/mvp-swift"
        ),
        // The M1 e2e client: starts interop/zig-peer, runs the MVP checks
        // against it over TCP and prints TAP (`just mvp-e2e`).
        .executableTarget(
            name: "mvp-e2e",
            dependencies: ["CapnpRPC", "CapnpNW", "CapnpMVPGen"],
            path: "interop/e2e-swift-client"
        ),
        .testTarget(
            name: "CapnpConformanceTests",
            dependencies: ["Capnp", "CapnpTestSchemas"]
        ),
        .testTarget(
            name: "CapnpRPCTests",
            // CapnpCore directly too: CoreSelftestTests calls a core test hook.
            dependencies: ["Capnp", "CapnpRPC", "CapnpNW", "CapnpMVP", "CapnpCore"]
        ),
        // Generated bindings for interop/schemas/mvp.capnp (M3): committed,
        // regenerated by tools/capnpc-swift. Replaces the hand-written
        // interop/mvp-swift bindings in M3-h.
        .target(
            name: "CapnpMVPGen",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/mvp-swift-gen"
        ),
        // The C++ test.capnp (TestAllTypes etc.) generated by capnpc-swift,
        // committed (Tests/capnp_testdata/test.request.bin is its input).
        .target(
            name: "CapnpTestSchemas",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "generated/conformance"
        ),
        // Crash-symbolication probe for scripts/check-dsym.sh: traps inside a
        // known Zig frame. Not a product; never shipped.
        .executableTarget(
            name: "TrapProbe",
            dependencies: ["CapnpCore"],
            path: "Examples/TrapProbe"
        ),
    ],
    swiftLanguageModes: [.v6]
)
