// swift-tools-version: 6.0
//
// capnp-swift: Cap'n Proto RPC for Swift apps on Apple platforms.
//
// The RPC core is capnp-zig (hash-pinned in core/build.zig.zon), built into
// the static CapnpCore.xcframework by `cd core && mise exec -- zig build
// xcframework`. Build that first; SwiftPM only links it.
//
// Packaging rules (plan §10): the XCFramework is static and ships no dynamic
// product; never bundle compiler-rt; never strip its DWARF. `platforms`
// lists what ships: macOS 15 and (M5) iOS 18.
import PackageDescription

let package = Package(
    name: "capnp-swift",
    platforms: [
        .macOS(.v15),
        // M5 (plan §8): the XCFramework ships ios-arm64 and
        // ios-arm64_x86_64-simulator slices (capnp-zig v0.21.0, handoff H1,
        // -Dfd-passing=false). iOS needs 18 for Synchronization.Mutex.
        .iOS(.v18),
    ],
    products: [
        // Pure-Swift message reader/builder (no Zig). M1 ships the subset the
        // MVP needs; M3 completes it.
        .library(name: "Capnp", targets: ["Capnp"]),
        // RPC runtime over the C ABI in CapnpCore.
        .library(name: "CapnpRPC", targets: ["CapnpRPC"]),
        // Network.framework transports (TCP in M1).
        .library(name: "CapnpNW", targets: ["CapnpNW"]),
        // M1 interop: the Swift side of `just mvp-e2e` (prints TAP).
        .executable(name: "mvp-e2e", targets: ["mvp-e2e"]),
    ],
    dependencies: [
        // Only the codegen driver links WasmKit (D6 option A: capnp.wasm
        // under WasmKit, no Wasmtime, no Python). The shipped libraries do
        // not depend on it.
        .package(url: "https://github.com/swiftwasm/WasmKit", from: "0.4.1"),
    ],
    targets: [
        // The release artifact (0.1.1). Development convenience: to hack on
        // the core itself, temporarily swap this for
        //   .binaryTarget(name: "CapnpCore", path: "CapnpCore.xcframework")
        // after `cd core && mise exec -- zig build xcframework -Dios=true`.
        .binaryTarget(
            name: "CapnpCore",
            url: "https://github.com/nullstyle/capnp-swift/releases/download/0.1.1/CapnpCore.xcframework.zip",
            checksum: "750f53096f825ba211607b27adcbdd6216e487b1f6c03b0b11135427af975340"
        ),
        .target(
            name: "Capnp"
        ),
        .target(
            name: "CapnpRPC",
            dependencies: ["CapnpCore", "Capnp"]
        ),
        .target(
            name: "CapnpNW",
            dependencies: ["CapnpRPC"]
        ),
        // Hand-written bindings for interop/schemas/mvp.capnp (plan §8, M1).
        // M3's capnpc-swift replaces them with generated code.
        .target(
            name: "CapnpMVP",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/mvp-swift"
        ),
        // The M1 e2e client: starts interop/zig-peer, runs the MVP checks
        // against it over TCP and prints TAP (`just mvp-e2e`).
        .executableTarget(
            name: "mvp-e2e",
            dependencies: ["CapnpRPC", "CapnpNW", "CapnpMVPGen"],
            path: "interop/e2e-swift-client-mvp"
        ),
        .testTarget(
            name: "CapnpConformanceTests",
            dependencies: ["Capnp", "CapnpTestSchemas", "CapnpTestVendor", "CapnpImportLib", "CapnpImportApp"]
        ),
        .testTarget(
            name: "CapnpRPCTests",
            // CapnpCore directly too: CoreSelftestTests calls a core test hook.
            dependencies: ["Capnp", "CapnpRPC", "CapnpNW", "CapnpMVP", "CapnpCore"]
        ),
        // Generated bindings for interop/schemas/mvp.capnp (M3): committed,
        // regenerated by tools/capnpc-swift. Replaces the hand-written
        // interop/mvp-swift bindings in M3-h.
        .target(
            name: "CapnpMVPGen",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/mvp-swift-gen"
        ),
        // The kaos/capnp_test vendor corpus (plan §8 M3 gate: the compiler's
        // `eval` binaries read through generated code).
        .target(
            name: "CapnpTestVendor",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "generated/vendor"
        ),
        // The M4 interop matrix bindings (interop/e2e/schemas, one module:
        // game_types + the five scenario schemas).
        .target(
            name: "CapnpE2E",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/e2e/gen"
        ),
        // The M4 interop peers following the capnp-zig e2e CLI contract.
        .executableTarget(
            name: "e2e-swift-server",
            dependencies: ["Capnp", "CapnpRPC", "CapnpNW", "CapnpE2E"],
            path: "interop/e2e-swift-server"
        ),
        .executableTarget(
            name: "e2e-swift-client",
            dependencies: ["Capnp", "CapnpRPC", "CapnpNW", "CapnpE2E"],
            path: "interop/e2e-swift-client"
        ),
        // The two-target import gate (plan §8 M3): app.capnp's generated
        // code imports the Lib module across the target boundary.
        .target(
            name: "CapnpImportLib",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "interop/importtest/lib-gen"
        ),
        .target(
            name: "CapnpImportApp",
            dependencies: ["Capnp", "CapnpRPC", "CapnpImportLib"],
            path: "interop/importtest/app-gen"
        ),
        // The C++ test.capnp (TestAllTypes etc.) generated by capnpc-swift,
        // committed (Tests/capnp_testdata/test.request.bin is its input).
        .target(
            name: "CapnpTestSchemas",
            dependencies: ["Capnp", "CapnpRPC"],
            path: "generated/conformance"
        ),
        // The D6 option-A pipeline runner: capnp.wasm under WasmKit plus the
        // native capnpc-swift plugin (tools/capnpc-driver).
        .executableTarget(
            name: "capnpc-driver",
            dependencies: [
                .product(name: "WasmKit", package: "WasmKit"),
                .product(name: "WasmKitWASI", package: "WasmKit"),
                .product(name: "WASI", package: "WasmKit"),
            ],
            path: "tools/capnpc-driver"
        ),
        // The command plugin: `swift package --allow-writing-to-package-directory
        // capnp-generate` (plus --check in CI; generated code is committed).
        .plugin(
            name: "CapnpGenerate",
            capability: .command(
                intent: .custom(verb: "capnp-generate", description: "Generate Swift bindings from .capnp schemas"),
                permissions: [.writeToPackageDirectory(reason: "Writes the generated Swift sources")]
            ),
            dependencies: ["capnpc-driver"],
            path: "Plugins/CapnpGenerate"
        ),
        // The M4 serialization bench (plan §8): Swift ping-pong vs
        // capnp-zig's bench/ping_pong.zig.
        .executableTarget(
            name: "bench-ping-pong",
            dependencies: ["Capnp"],
            path: "interop/bench-ping-pong"
        ),
        // Crash-symbolication probe for scripts/check-dsym.sh: traps inside a
        // known Zig frame. Not a product; never shipped.
        .executableTarget(
            name: "TrapProbe",
            dependencies: ["CapnpCore"],
            path: "Examples/TrapProbe"
        ),
    ],
    swiftLanguageModes: [.v6]
)
