// Generated by capnpc-swift from app.capnp. DO NOT EDIT.

import Capnp
import Lib

// Generated by capnpc-swift from app.capnp. DO NOT EDIT.

import Capnp

public struct UsesBox {
    public struct Reader: Sendable {
        let root: StructReader
        public init(_ root: StructReader) { self.root = root }
        public var box: Lib.Boxed.Reader {
            return Lib.Boxed.Reader(root.readStructOrDefault(0))
        }

    }

    public struct Builder {
        let root: StructBuilder
        public init(_ root: StructBuilder) { self.root = root; defaults() }
        public func initBox() -> Lib.Boxed.Builder {
            Lib.Boxed.Builder(root.initStruct(0, dataWords: 1, pointerWords: 0))
        }

        private func defaults() {
        }
    }

}

