// Generated by capnpc-swift from mvp.capnp. DO NOT EDIT.

import Capnp
import CapnpRPC

// Generated by capnpc-swift from mvp.capnp. DO NOT EDIT.

import Capnp
import CapnpRPC

public enum Listener {
    public static let interfaceID: UInt64 = 0x99991402f007d9a7

    public enum Method: UInt16 {
        case notify = 0
    }

    fileprivate static func decoding<T>(_ body: () throws -> T) throws -> T {
        do { return try body() } catch let error as CapnpError { throw RPCError.malformed("\(error)") }
    }

    public struct NotifyParams {
        public struct Reader: Sendable {
            let root: StructReader
            public init(_ root: StructReader) { self.root = root }
            public func msg() throws -> String {
                return try root.readTextOrDefault(0)
            }

        }

        public struct Builder {
            let root: StructBuilder
            /// Handler exports collected by the interface-typed setters.
            public var exports: [any ExportHandler] = []
            public init(_ root: StructBuilder) { self.root = root; defaults() }
            public func setMsg(_ v: String) { root.setText(0, v) }

            private func defaults() {
            }
        }

    }

    public struct NotifyResults {
        /// The built response bytes (a standalone message).
        public let bytes: [UInt8]
        public init(_ body: (inout Builder) -> Void = { _ in }) {
            let mb = MessageBuilder()
            var builder = Builder(mb.initRoot(dataWords: 0, pointerWords: 0))
            body(&builder)
            self.bytes = mb.toBytes()
        }

        public struct Reader: Sendable {
            let root: StructReader
            public init(_ root: StructReader) { self.root = root }
        }

        public struct Builder {
            let root: StructBuilder
            public init(_ root: StructBuilder) { self.root = root; defaults() }
            private func defaults() {
            }
        }

    }

    public protocol Server: Sendable {
        func notify(params: Listener.NotifyParams.Reader, caps: [CapTableEntry], on connection: RPCConnection) async throws -> Listener.NotifyResults
    }

    public struct Client: Sendable {
        public let target: CallTarget
        public let connection: RPCConnection
        public init(cap: CapRef, connection: RPCConnection) {
            self.target = .cap(cap)
            self.connection = connection
        }

        public init(pipelined: PipelinedCap, connection: RPCConnection) {
            self.target = .pipelined(pipelined)
            self.connection = connection
        }

        init(target: CallTarget, connection: RPCConnection) {
            self.target = target
            self.connection = connection
        }

        public func notify(_ body: (inout Listener.NotifyParams.Builder) -> Void = { _ in }) async throws -> Listener.NotifyResults.Reader {
            let mb = MessageBuilder()
            var params = Listener.NotifyParams.Builder(mb.initRoot(dataWords: 0, pointerWords: 1))
            body(&params)
            let result = try await connection.call(target, interface: Listener.interfaceID, method: Method.notify.rawValue, params: mb.toBytes(), caps: params.exports.map(CapSlot.export))
            return try decoding { try Listener.NotifyResults.Reader(Message(bytes: result.message).rootStruct()) }
        }

        public struct NotifyCall: Sendable {
            public let promise: RemotePromise
            public let connection: RPCConnection
            public func value() async throws -> Listener.NotifyResults.Reader {
                let result = try await promise.result()
                return try decoding { try Listener.NotifyResults.Reader(Message(bytes: result.message).rootStruct()) }
            }
        }

        public func sendNotify(_ body: (inout Listener.NotifyParams.Builder) -> Void = { _ in }) async throws -> NotifyCall {
            let mb = MessageBuilder()
            var params = Listener.NotifyParams.Builder(mb.initRoot(dataWords: 0, pointerWords: 1))
            body(&params)
            let promise = try await connection.send(target, interface: Listener.interfaceID, method: Method.notify.rawValue, params: mb.toBytes(), caps: params.exports.map(CapSlot.export))
            return NotifyCall(promise: promise, connection: connection)
        }

    }

    /// Serves a `Server` on a connection (pass it in `CapSlot.export`).
    /// Inherited interfaces dispatch here too (the Server protocol inherits
    /// their requirements; E-order holds for the whole closure).
    public struct Export: ExportHandler {
        public let server: any Server
        public init(_ server: any Server) { self.server = server }
        public func handle(_ call: InboundCall, on connection: isolated RPCConnection) async throws -> CallResponse {
            switch call.interfaceID {
            case Listener.interfaceID:
                switch call.methodID {
                case Listener.Method.notify.rawValue:
                    let params = try decoding { try Listener.NotifyParams.Reader(Message(bytes: call.params).rootStruct()) }
                    let results = try await server.notify(params: params, caps: call.caps, on: call.connection)
                    return CallResponse(message: results.bytes)
                default:
                    throw RPCError.unimplemented(reason: "Listener: no such method")
                }
            default:
                throw RPCError.unimplemented(reason: "Listener: wrong interface")
            }
        }
    }

}

public enum Greeter {
    public static let interfaceID: UInt64 = 0xf3031bb5a94706bb

    public enum Method: UInt16 {
        case greet = 0
    }

    fileprivate static func decoding<T>(_ body: () throws -> T) throws -> T {
        do { return try body() } catch let error as CapnpError { throw RPCError.malformed("\(error)") }
    }

    public struct GreetParams {
        public struct Reader: Sendable {
            let root: StructReader
            public init(_ root: StructReader) { self.root = root }
            public func name() throws -> String {
                return try root.readTextOrDefault(0)
            }

            /// The capability's index into the payload's cap table (nil when null).
            public func listenerCapIndex() -> UInt32? { (try? root.readCapabilityIndex(1)) ?? nil }

            /// The capability as a Client, resolved through the payload's cap table.
            public func listener(_ caps: [CapTableEntry], on connection: RPCConnection) -> Listener.Client? {
                guard let index = listenerCapIndex(), Int(index) < caps.count,
                    case .imported(let ref) = caps[Int(index)] else { return nil }
                return Listener.Client(cap: ref, connection: connection)
            }

        }

        public struct Builder {
            let root: StructBuilder
            /// Handler exports collected by the interface-typed setters.
            public var exports: [any ExportHandler] = []
            public init(_ root: StructBuilder) { self.root = root; defaults() }
            public func setName(_ v: String) { root.setText(0, v) }

            /// Export `server` for the call and point the field at it.
            public mutating func setListener(_ server: any Listener.Server) {
                root.setCapability(1, capIndex: UInt32(exports.count))
                exports.append(Listener.Export(server))
            }

            private func defaults() {
            }
        }

    }

    public struct GreetResults {
        /// The built response bytes (a standalone message).
        public let bytes: [UInt8]
        public init(_ body: (inout Builder) -> Void = { _ in }) {
            let mb = MessageBuilder()
            var builder = Builder(mb.initRoot(dataWords: 0, pointerWords: 1))
            body(&builder)
            self.bytes = mb.toBytes()
        }

        public struct Reader: Sendable {
            let root: StructReader
            public init(_ root: StructReader) { self.root = root }
            public func reply() throws -> String {
                return try root.readTextOrDefault(0)
            }

        }

        public struct Builder {
            let root: StructBuilder
            public init(_ root: StructBuilder) { self.root = root; defaults() }
            public func setReply(_ v: String) { root.setText(0, v) }

            private func defaults() {
            }
        }

    }

    public protocol Server: Sendable {
        func greet(params: Greeter.GreetParams.Reader, caps: [CapTableEntry], on connection: RPCConnection) async throws -> Greeter.GreetResults
    }

    public struct Client: Sendable {
        public let target: CallTarget
        public let connection: RPCConnection
        public init(cap: CapRef, connection: RPCConnection) {
            self.target = .cap(cap)
            self.connection = connection
        }

        public init(pipelined: PipelinedCap, connection: RPCConnection) {
            self.target = .pipelined(pipelined)
            self.connection = connection
        }

        init(target: CallTarget, connection: RPCConnection) {
            self.target = target
            self.connection = connection
        }

        public func greet(_ body: (inout Greeter.GreetParams.Builder) -> Void = { _ in }) async throws -> Greeter.GreetResults.Reader {
            let mb = MessageBuilder()
            var params = Greeter.GreetParams.Builder(mb.initRoot(dataWords: 0, pointerWords: 2))
            body(&params)
            let result = try await connection.call(target, interface: Greeter.interfaceID, method: Method.greet.rawValue, params: mb.toBytes(), caps: params.exports.map(CapSlot.export))
            return try decoding { try Greeter.GreetResults.Reader(Message(bytes: result.message).rootStruct()) }
        }

        public struct GreetCall: Sendable {
            public let promise: RemotePromise
            public let connection: RPCConnection
            public func value() async throws -> Greeter.GreetResults.Reader {
                let result = try await promise.result()
                return try decoding { try Greeter.GreetResults.Reader(Message(bytes: result.message).rootStruct()) }
            }
        }

        public func sendGreet(_ body: (inout Greeter.GreetParams.Builder) -> Void = { _ in }) async throws -> GreetCall {
            let mb = MessageBuilder()
            var params = Greeter.GreetParams.Builder(mb.initRoot(dataWords: 0, pointerWords: 2))
            body(&params)
            let promise = try await connection.send(target, interface: Greeter.interfaceID, method: Method.greet.rawValue, params: mb.toBytes(), caps: params.exports.map(CapSlot.export))
            return GreetCall(promise: promise, connection: connection)
        }

    }

    /// Serves a `Server` on a connection (pass it in `CapSlot.export`).
    /// Inherited interfaces dispatch here too (the Server protocol inherits
    /// their requirements; E-order holds for the whole closure).
    public struct Export: ExportHandler {
        public let server: any Server
        public init(_ server: any Server) { self.server = server }
        public func handle(_ call: InboundCall, on connection: isolated RPCConnection) async throws -> CallResponse {
            switch call.interfaceID {
            case Greeter.interfaceID:
                switch call.methodID {
                case Greeter.Method.greet.rawValue:
                    let params = try decoding { try Greeter.GreetParams.Reader(Message(bytes: call.params).rootStruct()) }
                    let results = try await server.greet(params: params, caps: call.caps, on: call.connection)
                    return CallResponse(message: results.bytes)
                default:
                    throw RPCError.unimplemented(reason: "Greeter: no such method")
                }
            default:
                throw RPCError.unimplemented(reason: "Greeter: wrong interface")
            }
        }
    }

}

