//! interop/zig-peer: a capnp-zig TCP server for the M1 e2e (plan §8, M1 e).
//!
//!   mise exec -- zig build            -> zig-out/bin/zig-peer
//!   zig-out/bin/zig-peer --host 127.0.0.1 --port 0
//!
//! It serves `Greeter` from interop/schemas/mvp.capnp on capnp-zig's Stable
//! `tcp.ServerSession.accept`, one connection at a time, and calls each
//! caller's `Listener` back. The bindings in gen/mvp.zig were generated by
//! capnp-zig's own compiler and plugin at the pinned tag (see gen/README.md).

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // -Dquic=true: the module root becomes src/lib_quic.zig, so
    // rpc.transport.quic is the real (quic-zig-backed) transport — the
    // M6 interop lanes need it (plan §8 M6; Experimental upstream too).
    const dep = b.dependency("capnpc_zig", .{ .target = target, .optimize = optimize, .quic = true });
    // The full module (RPC + the TCP transport), as an application uses it.
    const capnp = dep.module("capnpc-zig");

    const mvp = b.createModule(.{
        .root_source_file = b.path("gen/mvp.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{.{ .name = "capnpc-zig", .module = capnp }},
    });

    const exe = b.addExecutable(.{
        .name = "zig-peer",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .imports = &.{
                .{ .name = "capnpc-zig", .module = capnp },
                .{ .name = "mvp", .module = mvp },
            },
        }),
    });
    b.installArtifact(exe);

    const run = b.addRunArtifact(exe);
    run.addPassthruArgs();
    b.step("run", "Run zig-peer (pass --host/--port after --)").dependOn(&run.step);
}
