// Generated by the optional type-resolver specialization probe. DO NOT EDIT.
// App numbers are local to this file and are not a stable public naming scheme.
import Capnp

public typealias SpecializedRoot = App0

// struct:de16896bd1667aa0[]
public enum App0 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 8)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `textBox`() -> App1.Reader { App1.Reader(_raw.readStructOrDefault(0)) }
        public func `dataBox`() -> App2.Reader { App2.Reader(_raw.readStructOrDefault(1)) }
        public func `nestedBox`() -> App3.Reader { App3.Reader(_raw.readStructOrDefault(2)) }
        public func `listBox`() -> App4.Reader { App4.Reader(_raw.readStructOrDefault(3)) }
        public struct List4: Sendable {
            fileprivate let _raw: StructListReader
            public var count: Int { _raw.count }
            public var indices: Range<Int> { _raw.indices }
            public subscript(index: Int) -> App1.Reader { App1.Reader(_raw[index]) }
        }
        public func `boxes`() throws -> List4? { try _raw.readStructListOrDefault(4).map { List4(_raw: $0) } }
        public func `head`() -> App5.Reader { App5.Reader(_raw.readStructOrDefault(5)) }
        public func `lexical`() -> App6.Reader { App6.Reader(_raw.readStructOrDefault(6)) }
        public func `otherLexical`() -> App7.Reader { App7.Reader(_raw.readStructOrDefault(7)) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func initTextBox() -> App1.Builder { App1.Builder(_raw.initStruct(0, dataWords: 0, pointerWords: 1)) }
        public func initDataBox() -> App2.Builder { App2.Builder(_raw.initStruct(1, dataWords: 0, pointerWords: 1)) }
        public func initNestedBox() -> App3.Builder { App3.Builder(_raw.initStruct(2, dataWords: 0, pointerWords: 1)) }
        public func initListBox() -> App4.Builder { App4.Builder(_raw.initStruct(3, dataWords: 0, pointerWords: 1)) }
        public struct List4 {
            fileprivate let _raw: StructListBuilder
            public var count: Int { _raw.count }
            public subscript(index: Int) -> App1.Builder { App1.Builder(_raw[index]) }
        }
        public func initBoxes(_ count: Int) -> List4 { List4(_raw: _raw.initStructList(4, dataWords: 0, pointerWords: 1, count: count)) }
        public func initHead() -> App5.Builder { App5.Builder(_raw.initStruct(5, dataWords: 0, pointerWords: 3)) }
        public func initLexical() -> App6.Builder { App6.Builder(_raw.initStruct(6, dataWords: 0, pointerWords: 2)) }
        public func initOtherLexical() -> App7.Builder { App7.Builder(_raw.initStruct(7, dataWords: 0, pointerWords: 2)) }
    }
}

// struct:98267a3c94e49a04[98267a3c94e49a04:0=text;]
public enum App1 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 1)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `value`() throws -> String { try _raw.readTextOrDefault(0) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func setValue(_ value: String) { _raw.setText(0, value) }
    }
}

// struct:98267a3c94e49a04[98267a3c94e49a04:0=data;]
public enum App2 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 1)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `value`() throws -> [UInt8] { try _raw.readDataOrDefault(0) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func setValue(_ value: [UInt8]) { _raw.setData(0, value) }
    }
}

// struct:98267a3c94e49a04[98267a3c94e49a04:0=struct:98267a3c94e49a04[98267a3c94e49a04:0=text;];]
public enum App3 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 1)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `value`() -> App1.Reader { App1.Reader(_raw.readStructOrDefault(0)) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func initValue() -> App1.Builder { App1.Builder(_raw.initStruct(0, dataWords: 0, pointerWords: 1)) }
    }
}

// struct:98267a3c94e49a04[98267a3c94e49a04:0=list(uint16);]
public enum App4 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 1)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `value`() throws -> FixedSizeListReader<UInt16>? { try _raw.readFixedSizeListOrDefault(0, as: UInt16.self) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func initValue(_ count: Int) -> FixedSizeListBuilder<UInt16> { _raw.initFixedSizeList(0, count: count, as: UInt16.self) }
    }
}

// struct:e4712dde40ca5360[e4712dde40ca5360:0=text;]
public enum App5 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 3)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `value`() throws -> String { try _raw.readTextOrDefault(0) }
        public func `next`() -> App5.Reader { App5.Reader(_raw.readStructOrDefault(1)) }
        public struct List2: Sendable {
            fileprivate let _raw: StructListReader
            public var count: Int { _raw.count }
            public var indices: Range<Int> { _raw.indices }
            public subscript(index: Int) -> App5.Reader { App5.Reader(_raw[index]) }
        }
        public func `children`() throws -> List2? { try _raw.readStructListOrDefault(2).map { List2(_raw: $0) } }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func setValue(_ value: String) { _raw.setText(0, value) }
        public func initNext() -> App5.Builder { App5.Builder(_raw.initStruct(1, dataWords: 0, pointerWords: 3)) }
        public struct List2 {
            fileprivate let _raw: StructListBuilder
            public var count: Int { _raw.count }
            public subscript(index: Int) -> App5.Builder { App5.Builder(_raw[index]) }
        }
        public func initChildren(_ count: Int) -> List2 { List2(_raw: _raw.initStructList(2, dataWords: 0, pointerWords: 3, count: count)) }
    }
}

// struct:8102d485ded9d615[8102d485ded9d615:0=data;cd59598cc5f67e98:0=text;]
public enum App6 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 2)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `outer`() throws -> String { try _raw.readTextOrDefault(0) }
        public func `inner`() throws -> [UInt8] { try _raw.readDataOrDefault(1) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func setOuter(_ value: String) { _raw.setText(0, value) }
        public func setInner(_ value: [UInt8]) { _raw.setData(1, value) }
    }
}

// struct:8102d485ded9d615[8102d485ded9d615:0=text;cd59598cc5f67e98:0=data;]
public enum App7 {
    public static func initRoot(_ message: MessageBuilder) -> Builder { Builder(message.initRoot(dataWords: 0, pointerWords: 2)) }
    public struct Reader: Sendable {
        private let _raw: StructReader
        public init(_ raw: StructReader) { _raw = raw }
        public func `outer`() throws -> [UInt8] { try _raw.readDataOrDefault(0) }
        public func `inner`() throws -> String { try _raw.readTextOrDefault(1) }
    }
    public struct Builder {
        private let _raw: StructBuilder
        public init(_ raw: StructBuilder) { _raw = raw }
        public func setOuter(_ value: [UInt8]) { _raw.setData(0, value) }
        public func setInner(_ value: String) { _raw.setText(1, value) }
    }
}
