//! Resolve a concrete root into distinct, finite Swift struct applications.
//! Only the public facade is used. Graph identity includes effective bindings
//! of every lexical parameter, never node ID or raw Brand representation alone.
const std = @import("std");
const capnp = @import("capnp");
const schema = capnp.schema;
const resolver = capnp.type_resolver;

pub const Limits = struct { max_applications: usize = 256 };

/// Caller owns the returned source. Input nodes and metadata are borrowed only
/// during this call. Unsupported features fail before any source is returned.
pub fn generate(allocator: std.mem.Allocator, nodes: []const schema.Node, root_id: schema.Id, limits: Limits) ![]u8 {
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var graph = Graph{ .allocator = arena.allocator(), .nodes = nodes, .limits = limits };
    const root = try graph.node(root_id);
    const context = try resolver.Context.init(nodes, root, .{});
    const expression = schema.TypeExpression{ .type = .{ .@"struct" = .{ .type_id = root_id } } };
    try context.validate(expression);
    _ = try graph.register(&context, try context.resolve(expression));
    var output: std.Io.Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    try output.writer.writeAll("// Generated by the optional type-resolver specialization probe. DO NOT EDIT.\n// App numbers are local to this file and are not a stable public naming scheme.\nimport Capnp\n\npublic typealias SpecializedRoot = App0\n\n");
    for (graph.applications.items, 0..) |application, index| try emit(&output.writer, application, index, graph.applications.items);
    return output.toOwnedSlice();
}

const Shape = union(enum) { text, data, structure: usize, integers: []const u8, structures: usize };
const Field = struct { name: []const u8, offset: u32, shape: Shape };
const Application = struct { key: []const u8, node: *const schema.Node, fields: []const Field = &.{} };

const Graph = struct {
    allocator: std.mem.Allocator,
    nodes: []const schema.Node,
    limits: Limits,
    applications: std.ArrayList(Application) = .empty,

    fn node(self: *const Graph, id: schema.Id) !*const schema.Node {
        for (self.nodes) |*n| if (n.id == id) return n;
        return error.MissingNode;
    }

    fn register(self: *Graph, parent: *const resolver.Context, value: resolver.Type) anyerror!usize {
        const id = switch (value.expression.type) {
            .@"struct" => |s| s.type_id,
            else => return error.UnsupportedType,
        };
        var key: std.Io.Writer.Allocating = .init(self.allocator);
        try self.appendKey(&key.writer, parent, value, 0);
        for (self.applications.items, 0..) |existing, index| {
            if (std.mem.eql(u8, existing.key, key.written())) return index;
        }
        if (self.applications.items.len >= self.limits.max_applications) return error.ApplicationLimit;
        const n = try self.node(id);
        const structure = n.struct_node orelse return error.UnsupportedType;
        if (structure.is_group or structure.discriminant_count != 0 or structure.data_word_count != 0) return error.UnsupportedStruct;
        const context = try parent.enter(value);
        const index = self.applications.items.len;
        // Register before following fields: recursive applications reuse this slot.
        try self.applications.append(self.allocator, .{ .key = key.written(), .node = n });
        var fields: std.ArrayList(Field) = .empty;
        for (structure.fields) |definition| {
            try checkName(definition.name);
            const slot = definition.slot orelse return error.UnsupportedGroup;
            if (slot.offset >= structure.pointer_count) return error.InvalidSchema;
            if (slot.default_value) |default| switch (default) {
                .text, .data => |bytes| if (bytes.len != 0) return error.UnsupportedDefault,
                else => return error.UnsupportedDefault,
            };
            const expression = schema.TypeExpression{ .type = slot.type, .metadata = slot.type_metadata };
            try context.validate(expression);
            const resolved = try context.resolve(expression);
            const field_shape = try self.shape(&context, resolved);
            try fields.append(self.allocator, .{ .name = definition.name, .offset = slot.offset, .shape = field_shape });
        }
        self.applications.items[index].fields = try fields.toOwnedSlice(self.allocator);
        return index;
    }

    fn shape(self: *Graph, context: *const resolver.Context, value: resolver.Type) anyerror!Shape {
        if (value.unbound) return error.UnboundType;
        return switch (value.expression.type) {
            .text => .text,
            .data => .data,
            .@"struct" => .{ .structure = try self.register(context, value) },
            .list => blk: {
                const element = try context.listElement(value);
                if (element.unbound) return error.UnboundType;
                if (integerName(element.expression.type)) |name| break :blk .{ .integers = name };
                if (element.expression.type == .@"struct") break :blk .{ .structures = try self.register(context, element) };
                return error.UnsupportedList;
            },
            else => error.UnsupportedType,
        };
    }

    fn appendKey(self: *const Graph, w: *std.Io.Writer, context: *const resolver.Context, value: resolver.Type, depth: usize) anyerror!void {
        if (depth >= resolver.max_depth) return error.TypeKeyLimit;
        if (value.unbound) return error.UnboundType;
        switch (value.expression.type) {
            .list => {
                try w.writeAll("list(");
                try self.appendKey(w, context, try context.listElement(value), depth + 1);
                try w.writeByte(')');
            },
            inline .@"struct", .interface => |named| {
                try w.print("{s}:{x}[", .{ @tagName(value.expression.type), named.type_id });
                const entered = try context.enter(value);
                var scope = try self.node(named.type_id);
                var scopes: usize = 0;
                while (true) : (scopes += 1) {
                    if (scopes >= resolver.max_depth) return error.InvalidSchema;
                    for (scope.parameters, 0..) |_, parameter_index| {
                        try w.print("{x}:{d}=", .{ scope.id, parameter_index });
                        const parameter = schema.TypeExpression{ .type = .any_pointer, .metadata = .{ .any_pointer = .{ .parameter = .{ .scope_id = scope.id, .parameter_index = @intCast(parameter_index) } } } };
                        try self.appendKey(w, &entered, try entered.resolve(parameter), depth + 1);
                        try w.writeByte(';');
                    }
                    if (scope.scope_id == 0) break;
                    scope = try self.node(scope.scope_id);
                }
                try w.writeByte(']');
            },
            .@"enum" => |named| try w.print("enum:{x}", .{named.type_id}),
            .any_pointer => return error.UnsupportedType,
            else => try w.writeAll(@tagName(value.expression.type)),
        }
        // Called after every recursive piece, preventing exponentially large keys.
        if (w.end > 16 * 1024) return error.TypeKeyLimit;
    }
};

fn integerName(value: schema.Type) ?[]const u8 {
    return switch (value) {
        .int8 => "Int8",
        .int16 => "Int16",
        .int32 => "Int32",
        .int64 => "Int64",
        .uint8 => "UInt8",
        .uint16 => "UInt16",
        .uint32 => "UInt32",
        .uint64 => "UInt64",
        else => null,
    };
}

fn checkName(name: []const u8) !void {
    if (name.len == 0 or !std.ascii.isAlphabetic(name[0])) return error.UnsupportedFieldName;
    for (name) |c| if (!std.ascii.isAlphanumeric(c) and c != '_') return error.UnsupportedFieldName;
}

fn emit(w: *std.Io.Writer, application: Application, index: usize, applications: []const Application) !void {
    const structure = application.node.struct_node.?;
    try w.print("// {s}\npublic enum App{d} {{\n", .{ application.key, index });
    try w.print("    public static func initRoot(_ message: MessageBuilder) -> Builder {{ Builder(message.initRoot(dataWords: {d}, pointerWords: {d})) }}\n", .{ structure.data_word_count, structure.pointer_count });
    try w.writeAll("    public struct Reader: Sendable {\n        private let _raw: StructReader\n        public init(_ raw: StructReader) { _raw = raw }\n");
    for (application.fields, 0..) |field, ordinal| {
        switch (field.shape) {
            .text => try w.print("        public func `{s}`() throws -> String {{ try _raw.readTextOrDefault({d}) }}\n", .{ field.name, field.offset }),
            .data => try w.print("        public func `{s}`() throws -> [UInt8] {{ try _raw.readDataOrDefault({d}) }}\n", .{ field.name, field.offset }),
            .structure => |target| try w.print("        public func `{s}`() -> App{d}.Reader {{ App{d}.Reader(_raw.readStructOrDefault({d})) }}\n", .{ field.name, target, target, field.offset }),
            .integers => |name| try w.print("        public func `{s}`() throws -> FixedSizeListReader<{s}>? {{ try _raw.readFixedSizeListOrDefault({d}, as: {s}.self) }}\n", .{ field.name, name, field.offset, name }),
            .structures => |target| {
                try w.print("        public struct List{d}: Sendable {{\n            fileprivate let _raw: StructListReader\n            public var count: Int {{ _raw.count }}\n            public var indices: Range<Int> {{ _raw.indices }}\n            public subscript(index: Int) -> App{d}.Reader {{ App{d}.Reader(_raw[index]) }}\n        }}\n", .{ ordinal, target, target });
                try w.print("        public func `{s}`() throws -> List{d}? {{ try _raw.readStructListOrDefault({d}).map {{ List{d}(_raw: $0) }} }}\n", .{ field.name, ordinal, field.offset, ordinal });
            },
        }
    }
    try w.writeAll("    }\n    public struct Builder {\n        private let _raw: StructBuilder\n        public init(_ raw: StructBuilder) { _raw = raw }\n");
    for (application.fields, 0..) |field, ordinal| {
        const initial = std.ascii.toUpper(field.name[0]);
        const rest = field.name[1..];
        switch (field.shape) {
            .text => try w.print("        public func set{c}{s}(_ value: String) {{ _raw.setText({d}, value) }}\n", .{ initial, rest, field.offset }),
            .data => try w.print("        public func set{c}{s}(_ value: [UInt8]) {{ _raw.setData({d}, value) }}\n", .{ initial, rest, field.offset }),
            .structure => |target| {
                const shape = applications[target].node.struct_node.?;
                try w.print("        public func init{c}{s}() -> App{d}.Builder {{ App{d}.Builder(_raw.initStruct({d}, dataWords: {d}, pointerWords: {d})) }}\n", .{ initial, rest, target, target, field.offset, shape.data_word_count, shape.pointer_count });
            },
            .integers => |name| try w.print("        public func init{c}{s}(_ count: Int) -> FixedSizeListBuilder<{s}> {{ _raw.initFixedSizeList({d}, count: count, as: {s}.self) }}\n", .{ initial, rest, name, field.offset, name }),
            .structures => |target| {
                const shape = applications[target].node.struct_node.?;
                try w.print("        public struct List{d} {{\n            fileprivate let _raw: StructListBuilder\n            public var count: Int {{ _raw.count }}\n            public subscript(index: Int) -> App{d}.Builder {{ App{d}.Builder(_raw[index]) }}\n        }}\n", .{ ordinal, target, target });
                try w.print("        public func init{c}{s}(_ count: Int) -> List{d} {{ List{d}(_raw: _raw.initStructList({d}, dataWords: {d}, pointerWords: {d}, count: count)) }}\n", .{ initial, rest, ordinal, ordinal, field.offset, shape.data_word_count, shape.pointer_count });
            },
        }
    }
    try w.writeAll("    }\n}\n");
    if (index + 1 < applications.len) try w.writeByte('\n');
}
