//! capnpc-swift's Swift emitter.
//!
//! Input: the parsed CodeGeneratorRequest model from capnp-zig's Stable
//! `schema`/`request` modules. Output: one Swift source text per requested
//! schema file, ready for `swift build` with no post-processing (the
//! golden gate diffs it against a committed file).
//!
//! Emission rules (plan §6):
//!   - enums: RawRepresentable structs with static members; an unknown raw
//!     value stays itself (never traps)
//!   - unions: `Which` enums with `.unknownDiscriminant(UInt16)`
//!   - a wrong pointer kind reads as the field default; Text stays strict
//!   - scalar defaults apply when the struct's data section does not cover
//!     the field (schema evolution); pointer defaults when the pointer is
//!     null (embedded default message bytes)
//!   - no force unwraps in generated code (grep gate)
//!
//! v1 scope: structs (slots, groups, unions), enums, per-field list types.
//! Interfaces (Client/Server/Export), consts, `swift.capnp` annotations and
//! cross-file imports follow in M3-d/e.

const std = @import("std");
const capnp = @import("capnp");
const schema = capnp.schema;

const no_discriminant: u16 = 0xffff;

pub const Generator = struct {
    allocator: std.mem.Allocator,
    /// Names, literals and formatted snippets live here; freed wholesale.
    arena: std.heap.ArenaAllocator,
    /// Every schema node in the request, by id (the request outlives the
    /// generator; pointers into it are stable).
    node_map: std.AutoHashMapUnmanaged(schema.Id, *schema.Node) = .{},

    pub fn init(allocator: std.mem.Allocator, nodes: []schema.Node) !Generator {
        var self = Generator{ .allocator = allocator, .arena = std.heap.ArenaAllocator.init(allocator) };
        try self.node_map.ensureTotalCapacity(allocator, @intCast(nodes.len));
        for (nodes) |*node| {
            self.node_map.put(allocator, node.id, node) catch {};
        }
        return self;
    }

    pub fn deinit(self: *Generator) void {
        self.node_map.deinit(self.allocator);
        self.arena.deinit();
    }

    /// The arena allocator: everything the emitters allocate.
    fn scratch(self: *Generator) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn getNode(self: *Generator, id: schema.Id) ?*schema.Node {
        return self.node_map.get(id);
    }

    /// The node for `id`'s file: the outermost enclosing scope (a node whose
    /// own scope is 0).
    pub fn getFileNode(self: *Generator, id: schema.Id) ?*schema.Node {
        var node = self.getNode(id) orelse return null;
        while (node.scope_id != 0) {
            node = self.getNode(node.scope_id) orelse return null;
        }
        return node;
    }

    pub fn generateFile(self: *Generator, requested_file: schema.RequestedFile) ![]u8 {
        // The returned text is owned by `allocator` (the caller frees it);
        // interior scratch lives in the arena.
        var aw: std.Io.Writer.Allocating = .init(self.allocator);
        errdefer aw.deinit();
        const w = &aw.writer;

        const file_node = self.getNode(requested_file.id) orelse return error.MissingFileNode;
        try w.print("// Generated by capnpc-swift from {s}. DO NOT EDIT.\n\n", .{requested_file.filename});
        try w.writeAll("import Capnp\n\n");

        for (file_node.nested_nodes) |nested| {
            const node = self.getNode(nested.id) orelse continue;
            switch (node.kind) {
                .@"struct" => try self.emitStruct(w, node, 0),
                .@"enum" => try self.emitEnum(w, node, 0),
                .interface => try w.print("// interface {s} (M3-d)\n\n", .{node.display_name}),
                .@"const", .annotation, .file => {},
            }
        }
        return aw.toOwnedSlice();
    }

    // ------------------------------------------------ enums

    fn emitEnum(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        const enum_node = node.enum_node orelse return;
        const name = self.swiftTypeName(node);
        const pad = indentation(indent);
        try w.print("{s}public struct {s}: Hashable, Sendable {{\n", .{ pad, name });
        try w.print("{s}    public typealias RawValue = UInt16\n", .{pad});
        try w.print("{s}    public var rawValue: UInt16\n", .{pad});
        try w.print("{s}    public init(rawValue: UInt16) {{ self.rawValue = rawValue }}\n", .{pad});
        for (enum_node.enumerants, 0..) |enumerant, ordinal| {
            const member = try self.swiftMemberName(enumerant.name);
            try w.print("{s}    public static let {s} = {s}(rawValue: {d})\n", .{ pad, member, name, ordinal });
        }
        try w.print("{s}    public var isKnown: Bool {{\n", .{pad});
        try w.print("{s}        switch rawValue {{\n", .{pad});
        var cases: std.ArrayList(u8) = .empty;
        defer cases.deinit(self.scratch());
        for (0..enum_node.enumerants.len) |ordinal| {
            if (ordinal > 0) try cases.appendSlice(self.scratch(), ", ");
            var buf: [16]u8 = undefined;
            try cases.appendSlice(self.scratch(), std.fmt.bufPrint(&buf, "{d}", .{ordinal}) catch "0");
        }
        try w.print("{s}        case {s}: return true\n", .{ pad, cases.items });
        try w.print("{s}        default: return false\n", .{pad});
        try w.print("{s}        }}\n", .{pad});
        try w.print("{s}    }}\n", .{pad});
        try w.print("{s}}}\n\n", .{pad});
    }

    // ------------------------------------------------ structs

    fn emitStruct(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        try self.emitStructNamed(w, node, null, indent);
    }

    fn emitStructNamed(self: *Generator, w: *std.Io.Writer, node: *schema.Node, override_name: ?[]const u8, indent: usize) !void {
        const struct_node = node.struct_node orelse return;
        const name = override_name orelse self.swiftTypeName(node);
        const pad = indentation(indent);
        const has_union = struct_node.discriminant_count > 0;

        try w.print("{s}public struct {s} {{\n", .{ pad, name });

        // Nested named declarations first.
        for (node.nested_nodes) |nested| {
            const child = self.getNode(nested.id) orelse continue;
            switch (child.kind) {
                .@"struct" => {
                    const child_struct = child.struct_node orelse continue;
                    if (child_struct.is_group) continue; // groups ride on their field
                    try self.emitStructNamed(w, child, null, indent + 1);
                },
                .@"enum" => try self.emitEnum(w, child, indent + 1),
                else => {},
            }
        }
        // Group fields become nested types over the same storage, named from
        // the field (`foo :group` -> `Foo`).
        for (struct_node.fields) |field| {
            const group = field.group orelse continue;
            const group_node = self.getNode(group.type_id) orelse continue;
            const group_name = try self.groupTypeName(field);
            try self.emitStructNamed(w, group_node, group_name, indent + 1);
        }

        if (has_union) try self.emitWhichEnum(w, &struct_node, indent + 1);

        try self.emitReader(w, node, indent + 1);
        try self.emitBuilder(w, node, indent + 1);

        try w.print("{s}}}\n\n", .{pad});
    }

    fn emitWhichEnum(self: *Generator, w: *std.Io.Writer, struct_node: *const schema.StructNode, indent: usize) !void {
        const pad = indentation(indent);
        try w.print("{s}public enum Which: Equatable, Sendable {{\n", .{pad});
        for (struct_node.fields) |field| {
            if (field.discriminant_value == no_discriminant) continue;
            const member = try self.swiftMemberName(field.name);
            try w.print("{s}    case {s}\n", .{ pad, member });
        }
        try w.print("{s}    case unknownDiscriminant(UInt16)\n", .{pad});
        try w.print("{s}    public init(discriminant: UInt16) {{\n", .{pad});
        try w.print("{s}        switch discriminant {{\n", .{pad});
        for (struct_node.fields) |field| {
            if (field.discriminant_value == no_discriminant) continue;
            const member = try self.swiftMemberName(field.name);
            try w.print("{s}        case {d}: self = .{s}\n", .{ pad, field.discriminant_value, member });
        }
        try w.print("{s}        default: self = .unknownDiscriminant(discriminant)\n", .{pad});
        try w.print("{s}        }}\n", .{pad});
        try w.print("{s}    }}\n", .{pad});
        try w.print("{s}}}\n\n", .{pad});
    }

    fn emitReader(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        const struct_node = node.struct_node.?;
        const pad = indentation(indent);
        try w.print("{s}public struct Reader: Sendable {{\n", .{pad});
        try w.print("{s}    let root: StructReader\n", .{pad});
        try w.print("{s}    public init(_ root: StructReader) {{ self.root = root }}\n", .{pad});
        try self.emitReaderDefaultStatics(w, node, indent + 1);
        if (struct_node.discriminant_count > 0) {
            try w.print("{s}    public var which: Which {{ Which(discriminant: root.readUInt16(at: {d})) }}\n\n", .{ pad, struct_node.discriminant_offset });
        }
        for (struct_node.fields) |field| {
            try self.emitFieldReader(w, node, field, indent + 1);
        }
        try w.print("{s}}}\n\n", .{pad});
    }

    fn emitBuilder(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        const struct_node = node.struct_node.?;
        const pad = indentation(indent);
        try w.print("{s}public struct Builder {{\n", .{pad});
        try w.print("{s}    let root: StructBuilder\n", .{pad});
        try w.print("{s}    init(_ root: StructBuilder) {{ self.root = root; defaults() }}\n", .{pad});
        if (struct_node.discriminant_count > 0) {
            try w.print("{s}    public var which: Which {{ Which(discriminant: root.readUInt16(at: {d})) }}\n\n", .{ pad, struct_node.discriminant_offset });
        }
        for (struct_node.fields) |field| {
            try self.emitFieldBuilder(w, node, field, indent + 1);
        }
        try self.emitDefaults(w, node, indent);
        try w.print("{s}}}\n\n", .{pad});
    }

    /// `defaults()`: write every non-zero scalar default into a freshly
    /// allocated (zeroed) struct. Pointer defaults stay null; readers fall
    /// back to their bytes. Union discriminants start at 0 (the first
    /// declared member).
    fn emitDefaults(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        const struct_node = node.struct_node.?;
        const pad = indentation(indent);
        var body = std.Io.Writer.Allocating.init(self.scratch());
        defer body.deinit();
        const b = &body.writer;
        for (struct_node.fields) |field| {
            const slot = field.slot orelse continue;
            const dv = slot.default_value orelse continue;
            switch (slot.type) {
                .bool => if (dv.bool) try b.print("{s}    root.setBool(at: {d}, true)\n", .{ pad, slot.offset }),
                .int8 => if (dv.int8 != 0) try b.print("{s}    root.setInt8(at: {d}, {d})\n", .{ pad, slot.offset, dv.int8 }),
                .int16 => if (dv.int16 != 0) try b.print("{s}    root.setInt16(at: {d}, {d})\n", .{ pad, slot.offset, dv.int16 }),
                .int32 => if (dv.int32 != 0) try b.print("{s}    root.setInt32(at: {d}, {d})\n", .{ pad, slot.offset, dv.int32 }),
                .int64 => if (dv.int64 != 0) try b.print("{s}    root.setInt64(at: {d}, {d})\n", .{ pad, slot.offset, dv.int64 }),
                .uint8 => if (dv.uint8 != 0) try b.print("{s}    root.setUInt8(at: {d}, {d})\n", .{ pad, slot.offset, dv.uint8 }),
                .uint16 => if (dv.uint16 != 0) try b.print("{s}    root.setUInt16(at: {d}, {d})\n", .{ pad, slot.offset, dv.uint16 }),
                .uint32 => if (dv.uint32 != 0) try b.print("{s}    root.setUInt32(at: {d}, {d})\n", .{ pad, slot.offset, dv.uint32 }),
                .uint64 => if (dv.uint64 != 0) try b.print("{s}    root.setUInt64(at: {d}, {d})\n", .{ pad, slot.offset, dv.uint64 }),
                .float32 => {
                    const bits: u32 = @bitCast(dv.float32);
                    if (bits != 0) try b.print("{s}    root.setUInt32(at: {d}, 0x{x})\n", .{ pad, slot.offset, bits });
                },
                .float64 => {
                    const bits: u64 = @bitCast(dv.float64);
                    if (bits != 0) try b.print("{s}    root.setUInt64(at: {d}, 0x{x})\n", .{ pad, slot.offset, bits });
                },
                .@"enum" => {
                    const raw = dv.@"enum";
                    if (raw != 0) try b.print("{s}    root.setEnum16(at: {d}, {d})\n", .{ pad, slot.offset, raw });
                },
                else => {},
            }
        }
        try w.print("{s}    private func defaults() {{\n", .{pad});
        if (body.written().len == 0) {
            try w.print("{s}    }}\n", .{pad});
        } else {
            try w.writeAll(body.written());
            try w.print("{s}    }}\n", .{pad});
        }
    }

    // ------------------------------------------------ fields

    fn emitFieldReader(self: *Generator, w: *std.Io.Writer, parent: *schema.Node, field: schema.Field, indent: usize) !void {
        const pad = indentation(indent);
        const name = try self.fieldAccessorName(parent, field);
        if (field.group) |group| {
            _ = group;
            const type_name = try self.groupTypeName(field);
            try w.print("{s}public var {s}: {s}.Reader {{ {s}.Reader(root) }}\n\n", .{ pad, name, type_name, type_name });
            return;
        }
        const slot = field.slot orelse return; // void fields carry nothing
        const dv = slot.default_value;
        switch (slot.type) {
            .void => {},
            .bool => try self.readScalar(w, pad, name, "Bool", slot, dv, try self.fmtAt("readBool(at: {d})", slot.offset), "false", 1),
            .int8 => try self.readScalar(w, pad, name, "Int8", slot, dv, try self.fmtAt("readInt8(at: {d})", slot.offset), "0", 1),
            .int16 => try self.readScalar(w, pad, name, "Int16", slot, dv, try self.fmtAt("readInt16(at: {d})", slot.offset), "0", 2),
            .int32 => try self.readScalar(w, pad, name, "Int32", slot, dv, try self.fmtAt("readInt32(at: {d})", slot.offset), "0", 4),
            .int64 => try self.readScalar(w, pad, name, "Int64", slot, dv, try self.fmtAt("readInt64(at: {d})", slot.offset), "0", 8),
            .uint8 => try self.readScalar(w, pad, name, "UInt8", slot, dv, try self.fmtAt("readUInt8(at: {d})", slot.offset), "0", 1),
            .uint16 => try self.readScalar(w, pad, name, "UInt16", slot, dv, try self.fmtAt("readUInt16(at: {d})", slot.offset), "0", 2),
            .uint32 => try self.readScalar(w, pad, name, "UInt32", slot, dv, try self.fmtAt("readUInt32(at: {d})", slot.offset), "0", 4),
            .uint64 => try self.readScalar(w, pad, name, "UInt64", slot, dv, try self.fmtAt("readUInt64(at: {d})", slot.offset), "0", 8),
            .float32 => {
                const bits: u32 = if (dv) |v| @bitCast(v.float32) else 0;
                const fallback = try std.fmt.allocPrint(self.scratch(), "Float32(bitPattern: 0x{x})", .{bits});
                try self.readScalar(w, pad, name, "Float32", slot, dv, try self.fmtAt("readFloat32(at: {d})", slot.offset), fallback, 4);
            },
            .float64 => {
                const bits: u64 = if (dv) |v| @bitCast(v.float64) else 0;
                const fallback = try std.fmt.allocPrint(self.scratch(), "Float64(bitPattern: 0x{x})", .{bits});
                try self.readScalar(w, pad, name, "Float64", slot, dv, try self.fmtAt("readFloat64(at: {d})", slot.offset), fallback, 8);
            },
            .@"enum" => |e| {
                const enum_node = self.getNode(e.type_id) orelse return error.MissingEnumNode;
                const type_name = self.swiftRef(enum_node);
                const raw: u16 = if (dv) |v| v.@"enum" else 0;
                const has_default = raw != 0;
                if (has_default) {
                    try w.print("{s}public var {s}: {s} {{\n", .{ pad, name, type_name });
                    try w.print("{s}    if !root.covers(byteOffset: {d}, 2) {{ return {s}(rawValue: {d}) }}\n", .{ pad, slot.offset, type_name, raw });
                    try w.print("{s}    return {s}(rawValue: root.readUInt16(at: {d}))\n", .{ pad, type_name, slot.offset });
                    try w.print("{s}}}\n\n", .{pad});
                } else {
                    try w.print("{s}public var {s}: {s} {{ {s}(rawValue: root.readUInt16(at: {d})) }}\n\n", .{ pad, name, type_name, type_name, slot.offset });
                }
            },
            .text => {
                try w.print("{s}public func {s}() throws -> String {{\n", .{ pad, name });
                if (dv) |v| {
                    if (v.text.len > 0) {
                        const literal = try self.swiftStringLiteral(v.text);
                        try w.print("{s}    if root.isPointerNull({d}) {{ return {s} }}\n", .{ pad, slot.offset, literal });
                    }
                }
                try w.print("{s}    return try root.readTextOrDefault({d})\n", .{ pad, slot.offset });
                try w.print("{s}}}\n\n", .{pad});
            },
            .data => {
                try w.print("{s}public func {s}() throws -> [UInt8] {{\n", .{ pad, name });
                if (dv) |v| {
                    if (v.data.len > 0) {
                        const literal = try self.swiftByteArrayLiteral(v.data);
                        try w.print("{s}    if root.isPointerNull({d}) {{ return {s} }}\n", .{ pad, slot.offset, literal });
                    }
                }
                try w.print("{s}    return try root.readDataOrDefault({d})\n", .{ pad, slot.offset });
                try w.print("{s}}}\n\n", .{pad});
            },
            .@"struct" => |s| {
                const target = self.getNode(s.type_id) orelse return error.MissingStructNode;
                const type_name = self.swiftRef(target);
                const static_name = try self.staticDefaultName(name);
                try w.print("{s}public var {s}: {s}.Reader {{\n", .{ pad, name, type_name });
                if (dv) |v| {
                    if (v.@"struct".message_bytes.len > 0) {
                        try w.print("{s}    if root.isPointerNull({d}) {{ return {s}.Reader(Self.{s}.rootStruct()) }}\n", .{ pad, slot.offset, type_name, static_name });
                    }
                }
                try w.print("{s}    return {s}.Reader(root.readStructOrDefault({d}))\n", .{ pad, type_name, slot.offset });
                try w.print("{s}}}\n\n", .{pad});
            },
            .list => |l| try self.emitListReader(w, pad, name, slot, l.element_type),
            .interface => {
                try w.print("{s}/// The capability's index into the payload's cap table (nil when null).\n", .{pad});
                try w.print("{s}public func {s}CapIndex() -> UInt32? {{ (try? root.readCapabilityIndex({d})) ?? nil }}\n\n", .{ pad, name, slot.offset });
            },
            .any_pointer => {
                try w.print("{s}public var {s}: Bool {{ root.isPointerNull({d}) }}\n\n", .{ pad, try self.suffixedIdentifier(name, "IsNull"), slot.offset });
            },
        }
    }

    /// `private static let <Field>Default[Bytes]` for every struct field
    /// with a non-empty pointer default, at Reader scope.
    fn emitReaderDefaultStatics(self: *Generator, w: *std.Io.Writer, node: *schema.Node, indent: usize) !void {
        const struct_node = node.struct_node.?;
        const pad = indentation(indent);
        for (struct_node.fields) |field| {
            const slot = field.slot orelse continue;
            const dv = slot.default_value orelse continue;
            switch (slot.type) {
                .@"struct" => {
                    if (dv.@"struct".message_bytes.len == 0) continue;
                    const name = try self.fieldAccessorName(node, field);
                    const static_name = try self.staticDefaultName(name);
                    const bytes = try self.swiftByteArrayLiteral(dv.@"struct".message_bytes);
                    try w.print("{s}static let {s}Bytes = {s}\n", .{ pad, static_name, bytes });
                    try w.print("{s}static let {s} = CapnpDefaultMessage(bytes: {s}Bytes)\n", .{ pad, static_name, static_name });
                },
                else => {},
            }
        }
    }

    fn fmtAt(self: *Generator, comptime fmt: []const u8, offset: u32) ![]const u8 {
        return std.fmt.allocPrint(self.scratch(), fmt, .{offset});
    }

    fn readScalar(
        self: *Generator,
        w: *std.Io.Writer,
        pad: []const u8,
        name: []const u8,
        swift_type: []const u8,
        slot: schema.FieldSlot,
        dv: ?schema.Value,
        getter_fmt: []const u8,
        fallback: []const u8,
        width: usize,
    ) !void {
        _ = self;
        const getter = getter_fmt;
        const has_default = switch (dv orelse schema.Value{ .void = {} }) {
            .void => false,
            .bool => |v| v,
            .int8 => |v| v != 0,
            .int16 => |v| v != 0,
            .int32 => |v| v != 0,
            .int64 => |v| v != 0,
            .uint8 => |v| v != 0,
            .uint16 => |v| v != 0,
            .uint32 => |v| v != 0,
            .uint64 => |v| v != 0,
            .float32 => |v| @as(u32, @bitCast(v)) != 0,
            .float64 => |v| @as(u64, @bitCast(v)) != 0,
            .@"enum" => |v| v != 0,
            else => false,
        };
        if (has_default) {
            try w.print("{s}public var {s}: {s} {{\n", .{ pad, name, swift_type });
            try w.print("{s}    if !root.covers(byteOffset: {d}, {d}) {{ return {s} }}\n", .{ pad, slot.offset, width, fallback });
            try w.print("{s}    return root.{s}\n", .{ pad, getter });
            try w.print("{s}}}\n\n", .{pad});
        } else {
            try w.print("{s}public var {s}: {s} {{ root.{s} }}\n\n", .{ pad, name, swift_type, getter });
        }
    }

    fn fixedListReader(w: *std.Io.Writer, pad: []const u8, name: []const u8, swift_scalar: []const u8, offset: u32) !void {
        try w.print("{s}public func {s}() throws -> FixedSizeListReader<{s}>? {{ try root.readFixedSizeListOrDefault({d}, as: {s}.self) }}\n\n", .{ pad, name, swift_scalar, offset, swift_scalar });
    }

    fn emitListReader(self: *Generator, w: *std.Io.Writer, pad: []const u8, name: []const u8, slot: schema.FieldSlot, element: *schema.Type) !void {
        switch (element.*) {
            .void, .interface => try w.print("{s}public func {s}() throws -> PointerListReader? {{ try root.readPointerListOrDefault({d}) }}\n\n", .{ pad, name, slot.offset }),
            .bool => try w.print("{s}public func {s}() throws -> BitListReader? {{ try root.readBoolListOrDefault({d}) }}\n\n", .{ pad, name, slot.offset }),
            .int8 => try fixedListReader(w, pad, name, "Int8", slot.offset),
            .int16 => try fixedListReader(w, pad, name, "Int16", slot.offset),
            .int32 => try fixedListReader(w, pad, name, "Int32", slot.offset),
            .int64 => try fixedListReader(w, pad, name, "Int64", slot.offset),
            .uint8 => try fixedListReader(w, pad, name, "UInt8", slot.offset),
            .uint16 => try fixedListReader(w, pad, name, "UInt16", slot.offset),
            .uint32 => try fixedListReader(w, pad, name, "UInt32", slot.offset),
            .uint64 => try fixedListReader(w, pad, name, "UInt64", slot.offset),
            .float32 => try w.print("{s}public func {s}() throws -> Float32ListReader? {{ try root.readFloat32ListOrDefault({d}) }}\n\n", .{ pad, name, slot.offset }),
            .float64 => try w.print("{s}public func {s}() throws -> Float64ListReader? {{ try root.readFloat64ListOrDefault({d}) }}\n\n", .{ pad, name, slot.offset }),
            .@"enum" => |e| {
                const enum_node = self.getNode(e.type_id) orelse return error.MissingEnumNode;
                const type_name = self.swiftRef(enum_node);
                try w.print("{s}public func {s}() throws -> FixedSizeListReader<UInt16>? {{ try root.readFixedSizeListOrDefault({d}, as: UInt16.self) }}\n\n", .{ pad, name, slot.offset });
                try w.print("{s}public func {s}Elements() throws -> [{s}] {{\n", .{ pad, name, type_name });
                try w.print("{s}    guard let list = try {s}() else {{ return [] }}\n", .{ pad, name });
                try w.print("{s}    var out: [{s}] = []\n", .{ pad, type_name });
                try w.print("{s}    out.reserveCapacity(list.count)\n", .{pad});
                try w.print("{s}    for i in list.indices {{ out.append({s}(rawValue: list[i])) }}\n", .{ pad, type_name });
                try w.print("{s}    return out\n", .{pad});
                try w.print("{s}}}\n\n", .{pad});
            },
            .text, .data, .any_pointer, .list => try w.print("{s}public func {s}() throws -> PointerListReader? {{ try root.readPointerListOrDefault({d}) }}\n\n", .{ pad, name, slot.offset }),
            .@"struct" => |s| {
                const element_node = self.getNode(s.type_id) orelse return error.MissingStructNode;
                const element_name = self.swiftRef(element_node);
                const list_type = try self.capitalized(name);
                try w.print("{s}public struct {s}List: Sendable {{\n", .{ pad, list_type });
                try w.print("{s}    public let list: StructListReader\n", .{pad});
                try w.print("{s}    public var count: Int {{ list.count }}\n", .{pad});
                try w.print("{s}    public var indices: Range<Int> {{ list.indices }}\n", .{pad});
                try w.print("{s}    public subscript(index: Int) -> {s}.Reader {{ {s}.Reader(list[index]) }}\n", .{ pad, element_name, element_name });
                try w.print("{s}}}\n\n", .{pad});
                try w.print("{s}public func {s}() throws -> {s}List? {{ (try root.readStructListOrDefault({d})).map({s}List.init) }}\n\n", .{ pad, name, list_type, slot.offset, list_type });
            },
        }
    }

    fn emitFieldBuilder(self: *Generator, w: *std.Io.Writer, parent: *schema.Node, field: schema.Field, indent: usize) !void {
        const pad = indentation(indent);
        const name = try self.fieldAccessorName(parent, field);
        if (field.group) |group| {
            _ = group;
            const type_name = try self.groupTypeName(field);
            try w.print("{s}public var {s}: {s}.Builder {{ {s}.Builder(root) }}\n\n", .{ pad, name, type_name, type_name });
            return;
        }
        const slot = field.slot orelse return;
        switch (slot.type) {
            .void => {},
            .bool => try self.buildScalar(w, pad, name, "Bool", slot, "setBool(at: {d}, newValue)", "readBool(at: {d})"),
            .int8 => try self.buildScalar(w, pad, name, "Int8", slot, "setInt8(at: {d}, newValue)", "readInt8(at: {d})"),
            .int16 => try self.buildScalar(w, pad, name, "Int16", slot, "setInt16(at: {d}, newValue)", "readInt16(at: {d})"),
            .int32 => try self.buildScalar(w, pad, name, "Int32", slot, "setInt32(at: {d}, newValue)", "readInt32(at: {d})"),
            .int64 => try self.buildScalar(w, pad, name, "Int64", slot, "setInt64(at: {d}, newValue)", "readInt64(at: {d})"),
            .uint8 => try self.buildScalar(w, pad, name, "UInt8", slot, "setUInt8(at: {d}, newValue)", "readUInt8(at: {d})"),
            .uint16 => try self.buildScalar(w, pad, name, "UInt16", slot, "setUInt16(at: {d}, newValue)", "readUInt16(at: {d})"),
            .uint32 => try self.buildScalar(w, pad, name, "UInt32", slot, "setUInt32(at: {d}, newValue)", "readUInt32(at: {d})"),
            .uint64 => try self.buildScalar(w, pad, name, "UInt64", slot, "setUInt64(at: {d}, newValue)", "readUInt64(at: {d})"),
            .float32 => try self.buildScalar(w, pad, name, "Float32", slot, "setFloat32(at: {d}, newValue)", "readFloat32(at: {d})"),
            .float64 => try self.buildScalar(w, pad, name, "Float64", slot, "setFloat64(at: {d}, newValue)", "readFloat64(at: {d})"),
            .@"enum" => |e| {
                const enum_node = self.getNode(e.type_id) orelse return error.MissingEnumNode;
                const type_name = self.swiftRef(enum_node);
                try w.print("{s}public var {s}: {s} {{\n", .{ pad, name, type_name });
                try w.print("{s}    get {{ {s}(rawValue: root.readUInt16(at: {d})) }}\n", .{ pad, type_name, slot.offset });
                try w.print("{s}    set {{ root.setEnum16(at: {d}, newValue.rawValue) }}\n", .{ pad, slot.offset });
                try w.print("{s}}}\n\n", .{pad});
            },
            .text => try w.print("{s}public func set{s}(_ v: String) {{ root.setText({d}, v) }}\n\n", .{ pad, try self.capitalized(name), slot.offset }),
            .data => try w.print("{s}public func set{s}(_ v: [UInt8]) {{ root.setData({d}, v) }}\n\n", .{ pad, try self.capitalized(name), slot.offset }),
            .@"struct" => |s| {
                const target = self.getNode(s.type_id) orelse return error.MissingStructNode;
                const target_node = target.struct_node.?;
                const type_name = self.swiftRef(target);
                const cap = try self.capitalized(name);
                try w.print("{s}public func init{s}() -> {s}.Builder {{\n", .{ pad, cap, type_name });
                try w.print("{s}    {s}.Builder(root.initStruct({d}, dataWords: {d}, pointerWords: {d}))\n", .{ pad, type_name, slot.offset, target_node.data_word_count, target_node.pointer_count });
                try w.print("{s}}}\n\n", .{pad});
            },
            .list => |l| try self.emitListBuilder(w, pad, name, slot, l.element_type),
            .interface => try w.print("{s}public func set{s}(capIndex: UInt32) {{ root.setCapability({d}, capIndex: capIndex) }}\n\n", .{ pad, try self.capitalized(name), slot.offset }),
            .any_pointer => {},
        }
    }

    fn buildScalar(self: *Generator, w: *std.Io.Writer, pad: []const u8, name: []const u8, swift_type: []const u8, slot: schema.FieldSlot, comptime setter_fmt: []const u8, comptime getter_fmt: []const u8) !void {
        const setter = try std.fmt.allocPrint(self.scratch(), setter_fmt, .{slot.offset});
        const getter = try std.fmt.allocPrint(self.scratch(), getter_fmt, .{slot.offset});
        try w.print("{s}public var {s}: {s} {{\n", .{ pad, name, swift_type });
        try w.print("{s}    get {{ root.{s} }}\n", .{ pad, getter });
        try w.print("{s}    set {{ root.{s} }}\n", .{ pad, setter });
        try w.print("{s}}}\n\n", .{pad});
    }

    fn emitListBuilder(self: *Generator, w: *std.Io.Writer, pad: []const u8, name: []const u8, slot: schema.FieldSlot, element: *schema.Type) !void {
        const cap = try self.capitalized(name);
        switch (element.*) {
            .void, .interface => try w.print("{s}public func init{s}(_ count: Int) -> PointerListBuilderSlice {{ root.initTextList({d}, count: count) }}\n\n", .{ pad, cap, slot.offset }),
            .bool => try w.print("{s}public func init{s}(_ count: Int) -> BitListBuilder {{ root.initBoolList({d}, count: count) }}\n\n", .{ pad, cap, slot.offset }),
            .int8 => try self.buildList(w, pad, name, slot, "Int8"),
            .int16 => try self.buildList(w, pad, name, slot, "Int16"),
            .int32 => try self.buildList(w, pad, name, slot, "Int32"),
            .int64 => try self.buildList(w, pad, name, slot, "Int64"),
            .uint8 => try self.buildList(w, pad, name, slot, "UInt8"),
            .uint16 => try self.buildList(w, pad, name, slot, "UInt16"),
            .uint32 => try self.buildList(w, pad, name, slot, "UInt32"),
            .uint64 => try self.buildList(w, pad, name, slot, "UInt64"),
            .float32 => try w.print("{s}public func init{s}(_ count: Int) -> FixedSizeListBuilder<UInt32> {{ root.initFloat32List({d}, count: count) }}\n\n", .{ pad, cap, slot.offset }),
            .float64 => try w.print("{s}public func init{s}(_ count: Int) -> FixedSizeListBuilder<UInt64> {{ root.initFloat64List({d}, count: count) }}\n\n", .{ pad, cap, slot.offset }),
            .@"enum" => try self.buildList(w, pad, name, slot, "UInt16"),
            .text, .data, .any_pointer, .list => try w.print("{s}public func init{s}(_ count: Int) -> PointerListBuilderSlice {{ root.initTextList({d}, count: count) }}\n\n", .{ pad, cap, slot.offset }),
            .@"struct" => |s| {
                const target = self.getNode(s.type_id) orelse return error.MissingStructNode;
                const target_node = target.struct_node.?;
                try w.print("{s}public func init{s}(_ count: Int) -> StructListBuilder {{\n", .{ pad, cap });
                try w.print("{s}    root.initStructList({d}, dataWords: {d}, pointerWords: {d}, count: count)\n", .{ pad, slot.offset, target_node.data_word_count, target_node.pointer_count });
                try w.print("{s}}}\n\n", .{pad});
            },
        }
    }

    fn buildList(self: *Generator, w: *std.Io.Writer, pad: []const u8, name: []const u8, slot: schema.FieldSlot, swift_scalar: []const u8) !void {
        const cap = try self.capitalized(name);
        try w.print("{s}public func init{s}(_ count: Int) -> FixedSizeListBuilder<{s}> {{ root.initFixedSizeList({d}, count: count, as: {s}.self) }}\n\n", .{ pad, cap, swift_scalar, slot.offset, swift_scalar });
    }

    // ------------------------------------------------ names

    /// The type name for a node: the last path segment of its display name,
    /// escaped for Swift.
    /// The declaration name: the last display-name segment, escaped.
    fn swiftTypeName(self: *Generator, node: *schema.Node) []const u8 {
        return self.swiftIdentifierAlloc(lastSegment(node.display_name)) catch "BadName";
    }

    /// A type reference, qualified from the file root so it resolves from
    /// any scope in the generated file.
    fn swiftRef(self: *Generator, node: *schema.Node) []const u8 {
        return self.swiftQualifiedTypeName(node) catch "BadName";
    }

    /// The node's Swift name qualified from the file root (`Outer.Inner`),
    /// so references resolve from any scope in the generated file.
    fn swiftQualifiedTypeName(self: *Generator, node: *schema.Node) ![]const u8 {
        var chain: [16][]const u8 = undefined;
        var depth: usize = 0;
        var current: *schema.Node = node;
        while (true) {
            if (depth == chain.len) return error.ScopeTooDeep;
            if (current.kind == .file) break; // the file itself is not a scope
            chain[depth] = lastSegment(current.display_name);
            depth += 1;
            if (current.scope_id == 0) break;
            current = self.getNode(current.scope_id) orelse return error.MissingScopeNode;
        }
        var buf: std.ArrayList(u8) = .empty;
        var i: usize = depth;
        while (i > 0) {
            i -= 1;
            if (i + 1 != depth) try buf.append(self.scratch(), '.');
            const piece = try self.swiftIdentifierAlloc(chain[i]);
            try buf.appendSlice(self.scratch(), piece);
        }
        return buf.toOwnedSlice(self.scratch());
    }

    fn lastSegment(display_name: []const u8) []const u8 {
        if (std.mem.lastIndexOfScalar(u8, display_name, ':')) |i| {
            return display_name[i + 1 ..];
        }
        return display_name;
    }

    /// A member (field, enumerant, case) name, escaped for Swift.
    fn swiftMemberName(self: *Generator, name: []const u8) ![]const u8 {
        return self.swiftIdentifierAlloc(name);
    }

    fn fieldAccessorName(self: *Generator, parent: *schema.Node, field: schema.Field) ![]const u8 {
        var name = try self.swiftMemberName(field.name);
        // `which` collides with the generated union accessor.
        if (parent.struct_node != null and parent.struct_node.?.discriminant_count > 0 and std.mem.eql(u8, field.name, "which")) {
            name = try self.scratch().dupe(u8, "which_");
        }
        return name;
    }

    /// `foo` -> `fooSuffix`; an escaped name keeps the suffix inside the
    /// backticks (`` `any` + IsNull`` would parse as two identifiers).
    fn suffixedIdentifier(self: *Generator, name: []const u8, suffix: []const u8) ![]const u8 {
        if (name.len > 0 and name[0] == '`') {
            return std.fmt.allocPrint(self.scratch(), "`{s}{s}`", .{ name[1 .. name.len - 1], suffix });
        }
        return std.fmt.allocPrint(self.scratch(), "{s}{s}", .{ name, suffix });
    }

    fn groupTypeName(self: *Generator, field: schema.Field) ![]const u8 {
        return self.capitalized(try self.swiftMemberName(field.name));
    }

    fn staticDefaultName(self: *Generator, accessor: []const u8) ![]const u8 {
        const cap = try self.capitalized(accessor);
        return std.fmt.allocPrint(self.scratch(), "{s}Default", .{cap});
    }

    /// `fooBar` -> `FooBar`; backticks are preserved around the result.
    fn capitalized(self: *Generator, name: []const u8) ![]const u8 {
        if (name.len == 0) return name;
        const inner = if (name[0] == '`') name[1 .. name.len - 1] else name;
        if (inner.len == 0) return name;
        var buf: std.ArrayList(u8) = .empty;
        errdefer buf.deinit(self.scratch());
        if (name[0] == '`') try buf.append(self.scratch(), '`');
        try buf.append(self.scratch(), std.ascii.toUpper(inner[0]));
        try buf.appendSlice(self.scratch(), inner[1..]);
        if (name[0] == '`') try buf.append(self.scratch(), '`');
        return buf.toOwnedSlice(self.scratch());
    }

    fn swiftIdentifierAlloc(self: *Generator, name: []const u8) ![]const u8 {
        var buf: std.ArrayList(u8) = .empty;
        errdefer buf.deinit(self.scratch());
        for (name) |c| {
            if (std.ascii.isAlphanumeric(c) or c == '_') {
                try buf.append(self.scratch(), c);
            } else {
                try buf.append(self.scratch(), '_');
            }
        }
        if (buf.items.len == 0 or std.ascii.isDigit(buf.items[0])) {
            try buf.insert(self.scratch(), 0, '_');
        }
        if (isSwiftKeyword(buf.items)) {
            var escaped: std.ArrayList(u8) = .empty;
            errdefer escaped.deinit(self.scratch());
            try escaped.append(self.scratch(), '`');
            try escaped.appendSlice(self.scratch(), buf.items);
            try escaped.append(self.scratch(), '`');
            return escaped.toOwnedSlice(self.scratch());
        }
        return buf.toOwnedSlice(self.scratch());
    }

    fn swiftStringLiteral(self: *Generator, text: []const u8) ![]const u8 {
        var buf: std.ArrayList(u8) = .empty;
        errdefer buf.deinit(self.scratch());
        try buf.append(self.scratch(), '"');
        for (text) |c| {
            switch (c) {
                '"' => try buf.appendSlice(self.scratch(), "\\\""),
                '\\' => try buf.appendSlice(self.scratch(), "\\\\"),
                '\n' => try buf.appendSlice(self.scratch(), "\\n"),
                '\r' => try buf.appendSlice(self.scratch(), "\\r"),
                '\t' => try buf.appendSlice(self.scratch(), "\\t"),
                else => {
                    if (c < 0x20 or c == 0x7f) {
                        var hex: [16]u8 = undefined;
                        const digits = std.fmt.bufPrint(&hex, "{x}", .{c}) catch "0";
                        try buf.appendSlice(self.scratch(), "\\u{");
                        try buf.appendSlice(self.scratch(), digits);
                        try buf.append(self.scratch(), '}');
                    } else {
                        try buf.append(self.scratch(), c);
                    }
                },
            }
        }
        try buf.append(self.scratch(), '"');
        return buf.toOwnedSlice(self.scratch());
    }

    fn swiftByteArrayLiteral(self: *Generator, bytes: []const u8) ![]const u8 {
        var buf: std.ArrayList(u8) = .empty;
        errdefer buf.deinit(self.scratch());
        try buf.appendSlice(self.scratch(), "[UInt8]([");
        for (bytes, 0..) |b, i| {
            if (i > 0) try buf.appendSlice(self.scratch(), ", ");
            var hex: [4]u8 = undefined;
            const digits = std.fmt.bufPrint(&hex, "{x}", .{b}) catch "0";
            try buf.appendSlice(self.scratch(), "0x");
            try buf.appendSlice(self.scratch(), digits);
        }
        try buf.appendSlice(self.scratch(), "])");
        return buf.toOwnedSlice(self.scratch());
    }
};

fn indentation(level: usize) []const u8 {
    const spaces = "                                ";
    return spaces[0 .. @min(level, 8) * 4];
}

const swift_keywords = std.StaticStringMap(void).initComptime(.{
    .{"associatedtype"}, .{"class"},      .{"deinit"},        .{"enum"},          .{"extension"},
    .{"fileprivate"},     .{"func"},      .{"import"},        .{"init"},          .{"inout"},
    .{"internal"},        .{"let"},       .{"open"},          .{"operator"},      .{"private"},
    .{"precedencegroup"}, .{"protocol"},  .{"public"},        .{"rethrows"},      .{"static"},
    .{"struct"},          .{"subscript"}, .{"typealias"},     .{"var"},           .{"where"},
    .{"actor"},           .{"any"},       .{"as"},            .{"await"},         .{"async"},
    .{"break"},           .{"case"},      .{"catch"},         .{"continue"},      .{"default"},
    .{"defer"},           .{"do"},        .{"else"},          .{"fallthrough"},   .{"false"},
    .{"for"},             .{"guard"},     .{"if"},            .{"in"},            .{"is"},
    .{"nil"},             .{"repeat"},    .{"return"},        .{"self"},          .{"Self"},
    .{"super"},           .{"switch"},    .{"throw"},         .{"throws"},        .{"true"},
    .{"try"},             .{"while"},     .{"some"},          .{"each"},          .{"package"},
    .{"lazy"},            .{"weak"},      .{"unowned"},       .{"mutating"},      .{"override"},
    .{"final"},           .{"required"},  .{"convenience"},   .{"borrowing"},     .{"consuming"},
    .{"copying"},         .{"macro"},     .{"nonisolated"},   .{"distributed"},   .{"sending"},
});

fn isSwiftKeyword(name: []const u8) bool {
    return swift_keywords.has(name);
}

test "node map resolves nested nodes by id" {
    const a = std.testing.allocator;
    var no_nested = [_]schema.Node.NestedNode{};
    var no_annotations = [_]schema.AnnotationUse{};
    var file_nested = [_]schema.Node.NestedNode{.{ .name = "Greeter", .id = 2 }};
    const file_node = schema.Node{
        .id = 1,
        .display_name = "/x/mvp.capnp",
        .display_name_prefix_length = 3,
        .scope_id = 0,
        .nested_nodes = file_nested[0..],
        .annotations = no_annotations[0..],
        .kind = .file,
        .struct_node = null,
        .enum_node = null,
        .interface_node = null,
        .const_node = null,
        .annotation_node = null,
    };
    const greeter = schema.Node{
        .id = 2,
        .display_name = "/x/mvp.capnp:Greeter",
        .display_name_prefix_length = 3,
        .scope_id = 1,
        .nested_nodes = no_nested[0..],
        .annotations = no_annotations[0..],
        .kind = .interface,
        .struct_node = null,
        .enum_node = null,
        .interface_node = null,
        .const_node = null,
        .annotation_node = null,
    };
    var nodes = [_]schema.Node{ file_node, greeter };
    var gen = try Generator.init(a, nodes[0..]);
    defer gen.deinit();
    try std.testing.expectEqual(@as(u64, 2), gen.getNode(2).?.id);
    try std.testing.expectEqual(@as(u64, 1), gen.getFileNode(2).?.id);
    try std.testing.expect(@as(?*schema.Node, null) == gen.getNode(7));
}

test "swift identifier escaping" {
    const a = std.testing.allocator;
    var gen = try Generator.init(a, &.{});
    defer gen.deinit();
    const kw = try gen.swiftMemberName("class");
    try std.testing.expectEqualStrings("`class`", kw);
    const plain = try gen.swiftMemberName("fooBar2");
    try std.testing.expectEqualStrings("fooBar2", plain);
    const digit = try gen.swiftMemberName("9lives");
    try std.testing.expectEqualStrings("_9lives", digit);
}
