//! capnpc-swift's Swift emitter.
//!
//! Input: the parsed CodeGeneratorRequest model from capnp-zig's Stable
//! `schema`/`request` modules. Output: one Swift source text per requested
//! schema file, ready for `swift build` with no post-processing (the
//! generated-shape gate diffs it against a committed golden).
//!
//! M3 grows this file; the shapes it must produce are pinned by
//! tests/golden/*.swift and the conformance suite in the main package.

const std = @import("std");
const capnp = @import("capnp");
const schema = capnp.schema;

pub const Generator = struct {
    allocator: std.mem.Allocator,
    /// Every schema node in the request, by id (the request outlives the
    /// generator; pointers into it are stable).
    node_map: std.AutoHashMapUnmanaged(schema.Id, *schema.Node) = .{},

    pub fn init(allocator: std.mem.Allocator, nodes: []schema.Node) !Generator {
        var self = Generator{ .allocator = allocator };
        try self.node_map.ensureTotalCapacity(allocator, @intCast(nodes.len));
        for (nodes) |*node| {
            self.node_map.put(allocator, node.id, node) catch {};
        }
        return self;
    }

    pub fn deinit(self: *Generator) void {
        self.node_map.deinit(self.allocator);
    }

    pub fn getNode(self: *Generator, id: schema.Id) ?*schema.Node {
        return self.node_map.get(id);
    }

    /// The node for `id`'s file: the outermost enclosing scope (a node whose
    /// own scope is 0).
    pub fn getFileNode(self: *Generator, id: schema.Id) ?*schema.Node {
        var node = self.getNode(id) orelse return null;
        while (node.scope_id != 0) {
            node = self.getNode(node.scope_id) orelse return null;
        }
        return node;
    }

    pub fn generateFile(self: *Generator, requested_file: schema.RequestedFile) ![]u8 {
        var aw: std.Io.Writer.Allocating = .init(self.allocator);
        errdefer aw.deinit();
        const w = &aw.writer;

        const file_node = self.getNode(requested_file.id) orelse return error.MissingFileNode;
        try w.print("// Generated by capnpc-swift from {s}. DO NOT EDIT.\n", .{requested_file.filename});
        try w.print("// (stub emitter: M3-a pipeline check)\n\n", .{});

        for (file_node.nested_nodes) |nested| {
            const node = self.getNode(nested.id) orelse continue;
            try self.emitDeclarationStub(w, node);
        }
        return aw.toOwnedSlice();
    }

    fn emitDeclarationStub(self: *Generator, w: *std.Io.Writer, node: *schema.Node) !void {
        const kind = switch (node.kind) {
            .file => "file",
            .@"struct" => "struct",
            .@"enum" => "enum",
            .interface => "interface",
            .@"const" => "const",
            .annotation => "annotation",
        };
        try w.print("// {s}: {s} 0x{x}\n", .{ node.display_name, kind, node.id });
        if (node.kind == .interface) {
            if (node.interface_node) |iface| {
                for (iface.methods) |method| {
                    try w.print("//   func {s} (params 0x{x}, results 0x{x}{s})\n", .{
                        method.name,
                        method.param_struct_type,
                        method.result_struct_type,
                        if (method.isStreaming()) ", streaming" else "",
                    });
                }
            }
        }
        _ = self;
    }
};

/// The schema compiler's display_name is `<import prefix>/path/file.capnp:<nested...>`;
/// everything after the prefix length is the relative path we print.
fn displayNameBase(display_name: []const u8, prefix_length: u32) []const u8 {
    if (prefix_length < display_name.len) return display_name[prefix_length..];
    return display_name;
}

test "node map resolves nested nodes by id" {
    const a = std.testing.allocator;
    var no_nested = [_]schema.Node.NestedNode{};
    var no_annotations = [_]schema.AnnotationUse{};
    var file_nested = [_]schema.Node.NestedNode{.{ .name = "Greeter", .id = 2 }};
    const file_node = schema.Node{
        .id = 1,
        .display_name = "/x/mvp.capnp",
        .display_name_prefix_length = 3,
        .scope_id = 0,
        .nested_nodes = file_nested[0..],
        .annotations = no_annotations[0..],
        .kind = .file,
        .struct_node = null,
        .enum_node = null,
        .interface_node = null,
        .const_node = null,
        .annotation_node = null,
    };
    const greeter = schema.Node{
        .id = 2,
        .display_name = "/x/mvp.capnp:Greeter",
        .display_name_prefix_length = 3,
        .scope_id = 1,
        .nested_nodes = no_nested[0..],
        .annotations = no_annotations[0..],
        .kind = .interface,
        .struct_node = null,
        .enum_node = null,
        .interface_node = null,
        .const_node = null,
        .annotation_node = null,
    };
    var nodes = [_]schema.Node{ file_node, greeter };
    var gen = try Generator.init(a, nodes[0..]);
    defer gen.deinit();
    try std.testing.expectEqual(@as(u64, 2), gen.getNode(2).?.id);
    try std.testing.expectEqual(@as(u64, 1), gen.getFileNode(2).?.id);
    try std.testing.expect(@as(?*schema.Node, null) == gen.getNode(7));
}
