// Generated by capnpc-swift from defaults.capnp. DO NOT EDIT.

import Capnp

public struct Inner {
    public struct Reader: Sendable {
        let root: StructReader
        public init(_ root: StructReader) { self.root = root }
        public var id: UInt32 { root.readUInt32(at: 0) }

        public func label() throws -> String {
            return try root.readTextOrDefault(0)
        }

    }

    public struct Builder {
        let root: StructBuilder
        init(_ root: StructBuilder) { self.root = root; defaults() }
        public var id: UInt32 {
            get { root.readUInt32(at: 0) }
            set { root.setUInt32(at: 0, newValue) }
        }

        public func setLabel(_ v: String) { root.setText(0, v) }

        private func defaults() {
        }
    }

}

public struct Color: Hashable, Sendable {
    public typealias RawValue = UInt16
    public var rawValue: UInt16
    public init(rawValue: UInt16) { self.rawValue = rawValue }
    public static let red = Color(rawValue: 0)
    public static let green = Color(rawValue: 1)
    public static let blue = Color(rawValue: 2)
    public var isKnown: Bool {
        switch rawValue {
        case 0, 1, 2: return true
        default: return false
        }
    }
}

public struct Widget {
    public struct Reader: Sendable {
        let root: StructReader
        public init(_ root: StructReader) { self.root = root }
        static let InnerDefaultBytes = [UInt8]([0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x32, 0x0, 0x0, 0x0, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x0, 0x0, 0x0])
        static let InnerDefault = CapnpDefaultMessage(bytes: InnerDefaultBytes)
        public var id: UInt32 {
            if !root.covers(byteOffset: 0, 4) { return 0 }
            return root.readUInt32(at: 0)
        }

        public var flag: Bool {
            if !root.covers(byteOffset: 32, 1) { return false }
            return root.readBool(at: 32)
        }

        public func name() throws -> String {
            if root.isPointerNull(0) { return "widget" }
            return try root.readTextOrDefault(0)
        }

        public func data() throws -> [UInt8] {
            if root.isPointerNull(1) { return [UInt8]([0x1, 0x2, 0x3]) }
            return try root.readDataOrDefault(1)
        }

        public func nums() throws -> FixedSizeListReader<UInt16>? { try root.readFixedSizeListOrDefault(2, as: UInt16.self) }

        public var inner: Inner.Reader {
            if root.isPointerNull(3) { return Inner.Reader(Self.InnerDefault.rootStruct()) }
            return Inner.Reader(root.readStructOrDefault(3))
        }

        public var color: Color {
            if !root.covers(byteOffset: 3, 2) { return Color(rawValue: 1) }
            return Color(rawValue: root.readUInt16(at: 3))
        }

    }

    public struct Builder {
        let root: StructBuilder
        init(_ root: StructBuilder) { self.root = root; defaults() }
        public var id: UInt32 {
            get { root.readUInt32(at: 0) }
            set { root.setUInt32(at: 0, newValue) }
        }

        public var flag: Bool {
            get { root.readBool(at: 32) }
            set { root.setBool(at: 32, newValue) }
        }

        public func setName(_ v: String) { root.setText(0, v) }

        public func setData(_ v: [UInt8]) { root.setData(1, v) }

        public func initNums(_ count: Int) -> FixedSizeListBuilder<UInt16> { root.initFixedSizeList(2, count: count, as: UInt16.self) }

        public func initInner() -> Inner.Builder {
            Inner.Builder(root.initStruct(3, dataWords: 1, pointerWords: 1))
        }

        public var color: Color {
            get { Color(rawValue: root.readUInt16(at: 3)) }
            set { root.setEnum16(at: 3, newValue.rawValue) }
        }

        private func defaults() {
        root.setUInt32(at: 0, 123)
        root.setBool(at: 32, true)
        root.setEnum16(at: 3, 1)
        }
    }

}

