// Generated by capnpc-swift from mvp.capnp. DO NOT EDIT.
// (stub emitter: M3-a pipeline check)

// mvp.capnp:Listener: interface 0x99991402f007d9a7
//   func notify (params 0x8c78aeaac1e34016, results 0xed6e77fd9f463210)
// mvp.capnp:Greeter: interface 0xf3031bb5a94706bb
//   func greet (params 0xffda27f4d94b00fa, results 0x97425e6ea00ddbbf)
